---
- name: backup steam deck
  hosts: localhost
  gather_facts: false

  tasks:
    - name: backup user configuration
      ansible.posix.synchronize:
        src: /home/deck/.config
        dest: "{{ lookup('ansible.builtin.env', 'sdcard') }}/rsync-backups/"

    - name: backup user variable data
      ansible.posix.synchronize:
        src: /home/deck/.var
        dest: "{{ lookup('ansible.builtin.env', 'sdcard') }}/rsync-backups/"
