---
# tasks file for flatpak-installs

- name: installing flatpak list
  community.general.flatpak:
    name: "{{ item }}"
    state: "{{ flatpak_installs_state }}"
  loop: "{{ flatpak_installs_packages }}"
