---
# tasks file for pacman-installs

- block:

  - name: disable steamos-readonly
    ansible.builtin.shell: steamos-readonly disable

  - name: initialize pacman
    ansible.builtin.shell: pacman-key --init

  - name: populate pacman
    ansible.builtin.shell: pacman-key --populate archlinux

  - name: install packages
    community.general.pacman:
      name: "{{ item }}"
      state: "{{ pacman_installs_state }}"
    loop: "{{ pacman_installs_packages }}"

  - name: enable steamos-readonly
    ansible.builtin.shell: steamos-readonly enable
    become: true

  become: true