---
# tasks file for pacman-installs

- name: disable steamos-readonly
  ansible.builtin.shell: steamos-readonly disable
  become: true

- name: initialize pacman
  ansible.builtin.shell: pacman-key --init
  become: true

- name: populate pacman
  ansible.builtin.shell: pacman-key --populate archlinux
  become: true

- name: install packages
  community.general.pacman:
    name: "{{ item }}"
    state: "{{ pacman_installs_state }}"
  loop: "{{ pacman_installs_packages }}"

- name: enable steamos-readonly
  ansible.builtin.shell: steamos-readonly enable
  become: true
