---
- name: install base flatpaks
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: installing flatpak list
      community.general.flatpak:
        name: "{{ item }}"
        method: user
        state: present
      loop:        
        - com.github.tchx84.Flatseal
        - net.davidotek.pupgui2
        - com.usebottles.bottles
