---
- name: restore steam deck
  hosts: all
  gather_facts: false

  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    storage_label: "sdinfra"
    storage_path: "/run/media/{{ storage_label }}"

  tasks:
    - name: "check for back-up storage"
      ansible.builtin.stat:
        path: "{{ storage_path }}"
      register: sdcard_check

    - name: fail if back-up storage was not detected
      fail:
        msg: "back-up storage was not detected: {{ storage_path }}"
      when: sdcard_check.stat.isdir is not defined

    - name: restore user configuration
      ansible.posix.synchronize:
        src: "{{ storage_path }}/rsync-backups/.config"
        dest: "{{ home }}/"
        mode: pull

    - name: restore user variable data
      ansible.posix.synchronize:
        src: "{{ storage_path }}/rsync-backups/.var"
        dest: "{{ home }}/"
        mode: pull

    - name: restore most saved game data
      ansible.posix.synchronize:
        src: "{{ storage_path }}/rsync-backups/userdata"
        dest: "{{ home }}/.local/share/Steam/"
        mode: pull
