---
- name: restore steam deck
  hosts: all
  gather_facts: false

  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    sdcard_label: "sdinfra"
    sdcard_path: "/run/media/{{ user }}/{{ sdcard_label }}"

  tasks:
    - name: "check for SD card with label: {{ sdcard_label }}"
      ansible.builtin.stat:
        path: "{{ sdcard_path }}"
      register: sdcard_check

    - name: fail if SD card was not detected
      fail:
        msg: SD card was not detected
      when: sdcard_check.stat.isdir is not defined

    - name: restore user configuration
      ansible.posix.synchronize:
        src: "{{ sdcard }}/rsync-backups/.config"
        dest: "{{ home }}/"
        mode: pull

    - name: restore user variable data
      ansible.posix.synchronize:
        src: "{{ sdcard }}/rsync-backups/.var"
        dest: "{{ home }}/"
        mode: pull

    - name: restore most saved game data
      ansible.posix.synchronize:
        src: "{{ sdcard }}/rsync-backups/userdata"
        dest: "{{ home }}/.local/share/Steam/"
        mode: pull
