---
- name: backup steam deck
  hosts: all
  gather_facts: true

  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    sdcard: "{{ lookup('ansible.builtin.env', 'sdcard') }}"
    timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

  tasks:
    - name: backup user configuration
      ansible.posix.synchronize:
        src: "{{ home }}/.config"
        dest: "{{ sdcard }}/rsync-backups/{{ timestamp }}/"

    - name: backup user variable data
      ansible.posix.synchronize:
        src: "{{ home }}/.var"
        dest: "{{ sdcard }}/rsync-backups/{{ timestamp }}/"

    - name: backup most saved game data
      ansible.posix.synchronize:
        src: "{{ home }}/.local/share/Steam/userdata"
        dest: "{{ sdcard }}/rsync-backups/{{ timestamp }}/"
