---
- name: restore steam deck
  hosts: localhost
  gather_facts: false

  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    sdcard: "{{ lookup('ansible.builtin.env', 'sdcard') }}"
    timestamp: "{{ lookup('ansible.builtin.env', 'timestamp') }}"

  tasks:
    - block:

      - name: restore user configuration
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/.config"
          dest: "{{ home }}/"
          mode: pull

      - name: restore user variable data
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/.var"
          dest: "{{ home }}/"
          mode: pull

      - name: restore most saved game data
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/userdata"
          dest: "{{ home }}/.local/share/Steam/"
          mode: pull

      when: lookup('ansible.builtin.env', 'timestamp') != ''

    - block:

      - name: restore error
        ansible.builtin.debug:
          msg: "Timestamp variable not set. Example: export timestamp=2022-12-31-23-59-59"
        

      - name: get available timestamps
        ansible.builtin.shell: "ls {{ sdcard }}/rsync-backups/"
        register: timestamps
        no_log: true

      - name: show available timestamps
        ansible.builtin.debug:
          msg: "{{ timestamps.stdout_lines }}"

      when: lookup('ansible.builtin.env', 'timestamp') == ''
      
    