---
- name: restore steam deck
  hosts: localhost
  gather_facts: false

  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    sdcard: "{{ lookup('ansible.builtin.env', 'sdcard') }}"
    timestamp: "{{ lookup('ansible.builtin.env', 'timestamp') }}"

  tasks:
    - block:
      - name: restore user configuration
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/.config"
          dest: "{{ home }}/.config"
          mode: pull

      - name: restore user variable data
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/.var"
          dest: "{{ home }}/.var"
          mode: pull

      - name: restore most saved game data
        ansible.posix.synchronize:
          src: "{{ sdcard }}/rsync-backups/{{ timestamp }}/.local"
          dest: "{{ home }}/.local/share/Steam/userdata"
          mode: pull
      when: lookup('ansible.builtin.env', 'timestamp') != ''

    - name: restore error
      ansible.builtin.debug:
        msg: "Timestamp variable not set. Example: export timestamp=2022-09-08-10-50-59"
      when: lookup('ansible.builtin.env', 'timestamp') == ''
      