---
- name: backup steam deck
  hosts: all
  gather_facts: true

  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    storage_label: "sdinfra"
    storage_path: "/run/media/{{ storage_label }}"

  tasks:
    - name: "check for back-up storage"
      ansible.builtin.stat:
        path: "{{ storage_path }}"
      register: sdcard_check

    - name: fail if back-up storage was not detected
      fail:
        msg: "back-up storage was not detected: {{ storage_path }}"
      when: sdcard_check.stat.isdir is not defined

    - name: ensure rsync-backup diretory is present
      ansible.builtin.file:
        path: "{{ storage_path }}/rsync-backups"
        state: directory

    - name: backup user configuration
      ansible.posix.synchronize:
        src: "{{ home }}/.config"
        dest: "{{ storage_path }}/rsync-backups"

    - name: backup user variable data
      ansible.posix.synchronize:
        src: "{{ home }}/.var"
        dest: "{{ storage_path }}/rsync-backups"

    - name: backup most saved game data
      ansible.posix.synchronize:
        src: "{{ home }}/.local/share/Steam/userdata"
        dest: "{{ storage_path }}/rsync-backups"
