---
- name: Main playbook
  hosts: all
  gather_facts: false

- name: import install playbook
  ansible.builtin.import_playbook: install.yml

- name: import configure playbook
  ansible.builtin.import_playbook: configure.yml
